// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Owlia.Data;

#nullable disable

namespace Owlia.Data.Migrations
{
    [DbContext(typeof(OwliaDbContext))]
    [Migration("20260828115414_AddSpeechPercentage")]
    partial class AddSpeechPercentage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Owlia.Data.Entities.SegmentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("EndMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SentimentLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SentimentScore")
                        .HasColumnType("REAL");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speaker")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("Owlia.Data.Entities.SessionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeakerCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Owlia.Data.Entities.SummaryEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyTakeawaysJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("SpeechPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("SummaryText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("Owlia.Data.Entities.SegmentEntity", b =>
                {
                    b.HasOne("Owlia.Data.Entities.SessionEntity", "Session")
                        .WithMany("Segments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Owlia.Data.Entities.SummaryEntity", b =>
                {
                    b.HasOne("Owlia.Data.Entities.SessionEntity", "Session")
                        .WithOne("Summary")
                        .HasForeignKey("Owlia.Data.Entities.SummaryEntity", "SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Owlia.Data.Entities.SessionEntity", b =>
                {
                    b.Navigation("Segments");

                    b.Navigation("Summary");
                });
#pragma warning restore 612, 618
        }
    }
}
